#cloud-config

################################################################################
# This config is used to set-up Drupal dev environment with OpenStack based on
# an Ubuntu 16.04 image.
# It's meant to be a base for Docker Compose Drupal stack to set up a full DEV
# environment.
# THIS SETUP IS ONLY FOR DEV, MUST NOT BE USED ON PRODUCTION.
#
# What this config is doing:
#   Install minimal packages: Git, Docker, Compass (with ruby),
#   Composer with minimal Php 7.
#   Run a generic script to install Docker-compose, Composer, Code sniffer.
#   Run a generic script to install this Docker-compose stack.
#   Run a generic script to install Drupal 8 with Composer and Bootstrap Sass.
#
################################################################################

# Adjust these commands to your needs and replace or add any other script.
# Note that these commands are executed by the root user, you can use su to pass
# it to ubuntu user.
runcmd:
  # Add Docker recommended packages and add user to Docker group, should not be
  # edited. this is required for Docker.
  - apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
  - usermod -aG docker ubuntu
  - wget -O /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64"
  - chown "ubuntu:ubuntu" /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  # External script to setup properly Docker-compose, and Drupal Docker Compose
  # dev stack (this project) with user ubuntu.
  - wget -O /home/ubuntu/setup-docker-stack.sh -q "https://raw.githubusercontent.com/Mogtofu33/docker-compose-drupal/master/openstack/setup_DDD_ubuntu16.sh"
  - chmod +x /home/ubuntu/setup-docker-stack.sh
  - chown "ubuntu:ubuntu" /home/ubuntu/setup-docker-stack.sh
  - su -c "/home/ubuntu/setup-docker-stack.sh" ubuntu
  ##############################################################################
  # This part is an example to install Drupal 8, it can be replaced by an other
  # specific script to clone an existing Drupal 8 project.
  # If you clone from a private repo you must add a deploy key in this config.
  #
  # Grab setup scripts for base Drupal 8 and run it as user ubuntu.
  - wget -O /home/ubuntu/setup-drupal8.sh -q "https://raw.githubusercontent.com/Mogtofu33/docker-compose-drupal/master/openstack/setup_DDD_D8_ubuntu16.sh"
  - chmod +x /home/ubuntu/setup-drupal8.sh
  - chown "ubuntu:ubuntu" /home/ubuntu/setup-drupal8.sh
  - su -c "/home/ubuntu/setup-drupal8.sh" ubuntu
  ##############################################################################
  # This part is an example to install Bootstrap Sass subtheme on Drupal 8 from
  # previous script.
  #
  # Grab setup scripts for Bootstrap subtheme and run it as user ubuntu.
  - wget -O /home/ubuntu/setup-d8-bootstrap.sh -q "https://raw.githubusercontent.com/Mogtofu33/docker-compose-drupal/master/openstack/setup_DDD_D8_Bootstrap_sass.sh"
  - chmod +x /home/ubuntu/setup-d8-bootstrap.sh
  - chown "ubuntu:ubuntu" /home/ubuntu/setup-d8-bootstrap.sh
  - su -c "/home/ubuntu/setup-d8-bootstrap.sh" ubuntu
################################################################################
# Basic, cloud config for Ubuntu 16.04 image with Docker.
# Setup Docker, minimal Php 7 for Composer and Compass with bootstrap.
packages:
  - software-properties-common
  - python
  - apt-transport-https
  - ca-certificates
  - git-core
  - docker-engine
  - php7.0-curl
  - php7.0-zip
  - php7.0-mbstring
  - php7.0-json
  - php7.0-opcache
  - php7.0-readline
  - php7.0-cli
  - php-cli
  - php-cli-prompt
  - php7.0-gd
  - php7.0-xml
  - ruby-full
  - ruby-compass
  - ruby-sass
  - ruby-bootstrap-sass
package_update: true
package_upgrade: true
# Set-up Docker for Ubuntu 16.04, see doc at:
# https://docs.docker.com/engine/installation/linux/ubuntu/
apt_sources:
 - source: deb https://apt.dockerproject.org/repo ubuntu-xenial main
   filename: docker.list
   key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: SKS 1.1.5+
      Comment: Hostname: keyserver.garden-lan.com

      mQINBFWln24BEADrBl5p99uKh8+rpvqJ48u4eTtjeXAWbslJotmC/CakbNSqOb9oddfzRvGV
      eJVERt/Q/mlvEqgnyTQy+e6oEYN2Y2kqXceUhXagThnqCoxcEJ3+KM4RmYdoe/BJ/J/6rHOj
      q7Omk24z2qB3RU1uAv57iY5VGw5p45uZB4C4pNNsBJXoCvPnTGAs/7IrekFZDDgVraPx/hdi
      wopQ8NltSfZCyu/jPpWFK28TR8yfVlzYFwibj5WKdHM7ZTqlA1tHIG+agyPf3Rae0jPMsHR6
      q+arXVwMccyOi+ULU0z8mHUJ3iEMIrpTX+80KaN/ZjibfsBOCjcfiJSB/acn4nxQQgNZigna
      32velafhQivsNREFeJpzENiGHOoyC6qVeOgKrRiKxzymj0FIMLru/iFF5pSWcBQB7PYlt8J0
      G80lAcPr6VCiN+4cNKv03SdvA69dCOj79PuO9IIvQsJXsSq96HB+TeEmmL+xSdpGtGdCJHHM
      1fDeCqkZhT+RtBGQL2SEdWjxbF43oQopocT8cHvyX6Zaltn0svoGs+wX3Z/H6/8P5anog43U
      65c0A+64Jj00rNDr8j31izhtQMRo892kGeQAaaxg4Pz6HnS7hRC+cOMHUU4HA7iMzHrouAdY
      eTZeZEQOA7SxtCME9ZnGwe2grxPXh/U/80WJGkzLFNcTKdv+rwARAQABtDdEb2NrZXIgUmVs
      ZWFzZSBUb29sIChyZWxlYXNlZG9ja2VyKSA8ZG9ja2VyQGRvY2tlci5jb20+iQIcBBABCgAG
      BQJWw7vdAAoJEFyzYeVS+w0QHysP/i37m4SyoOCVcnybl18vzwBEcp4VCRbXvHvOXty1gccV
      IV8/aJqNKgBV97lY3vrpOyiIeB8ETQegsrxFE7t/Gz0rsLObqfLEHdmn5iBJRkhLfCpzjeOn
      yB3Z0IJB6UogO/msQVYe5CXJl6uwr0AmoiCBLrVlDAktxVh9RWch0l0KZRX2FpHu8h+uM0/z
      ySqIidlYfLa3y5oHscU+nGU1i6ImwDTD3ysZC5jp9aVfvUmcESyAb4vvdcAHR+bXhA/RW8QH
      eeMFliWw7Z2jYHyuHmDnWG2yUrnCqAJTrWV+OfKRIzzJFBs4e88ru5h2ZIXdRepw/+COYj34
      LyzxR2cxr2u/xvxwXCkSMe7F4KZAphD+1ws61FhnUMi/PERMYfTFuvPrCkq4gyBjt3fFpZ2N
      R/fKW87QOeVcn1ivXl9id3MMs9KXJsg7QasT7mCsee2VIFsxrkFQ2jNpD+JAERRn9Fj4ArHL
      5TbwkkFbZZvSi6fr5h2GbCAXIGhIXKnjjorPY/YDX6X8AaHOW1zblWy/CFr6VFl963jrjJga
      g0G6tNtBZLrclZgWhOQpeZZ5Lbvz2ZA5CqRrfAVcwPNW1fObFIRtqV6vuVluFOPCMAAnOnqR
      02w9t17iVQjO3oVN0mbQi9vjuExXh1YoScVetiO6LSmlQfVEVRTqHLMgXyR/EMo7iQIcBBAB
      CgAGBQJXSWBlAAoJEFyzYeVS+w0QeH0QAI6btAfYwYPuAjfRUy9qlnPhZ+xt1rnwsUzsbmo8
      K3XTNh+l/R08nu0dsczw30Q1wju28fh1N8ay223+69f0+yICaXqR18AbGgFGKX7vo0gfEVax
      dItUN3eHNydGFzmeOKbAlrxIMECnSTG/TkFVYO9Ntlv9vSN2BupmTagTRErxLZKnVsWRzp+X
      elwlgU5BCZ6U6Ze8+bIc6F1bZstf17X8i6XNV/rOCLx2yP0hn1osoljoLPpW8nzkwvqYsYbC
      A28lMt1aqe0UWvRCqR0zxlKn17NZQqjbxcajEMCajoQ01MshmO5GWePViv2abCZ/iaC5zKqV
      T3deMJHLq7lum6qhA41E9gJH9QoqT+qgadheeFfoC1QP7cke+tXmYg2R39p3l5Hmm+JQbP4f
      9V5mpWExvHGCSbcatr35tnakIJZugq2ogzsm1djCSz9222RXl9OoFqsm1bNzA78+/cOt5N2c
      yhU0bM2T/zgh42YbDD+JDU/HSmxUIpU+wrGvZGM2FU/up0DRxOC4U1fL6HHlj8liNJWfEg3v
      hougOh66gGF9ik5j4eIlNoz6lst+gmvlZQ9/9hRDeoG+AbhZeIlQ4CCw+Y1j/+fUxIzKHPVK
      +aFJd+oJVNvbojJW/SgDdSMtFwqOvXyYcHl30Ws0gZUeDyAmNGZeJ3kFklnApDmeKK+OiQIi
      BBABCgAMBQJXe5zTBYMHhh+AAAoJEDG4FaMBBnSp7YMQAJqrXoBonZAq07B6qUaT3aBCgnY4
      JshbXmFb/XrrS75f7YJDPx2fJJdqrbYDIHHgOjzxvp3ngPpOpJzI5sYmkaugeoCO/KHu/+39
      XqgTB7fguzapRfbvuWp+qzPcHSdb9opnagfzKAze3DQnnLiwCPlsyvGpzC4KzXgV2ze/4raa
      Oye1kK7O0cHyapmn/q/TR3S8YapyXq5VpLThwJAw1SRDu0YxeXIAQiIfaSxT79EktoioW2CS
      V8/djt+gBjXnKYJJA8P1zzX7GNt/Rc2YG0Ot4v6tBW16xqFTg+n5JzbeK5cZ1jbIXXfCcaZJ
      yiM2MzYGhSJ9+EV7JYF05OAIWE4SGTRjXMquQ2oMLSwMCPQHm+FCD9PXQ0tHYx6tKT34wksd
      moWsdejl/n3NS+178mG1WI/lN079h3im2gRwOykMou/QWs3vGw/xDoOYHPV2gJ7To9BLVnVK
      /hROgdFLZFeyRScNzwKm57HmYMFA74tX601OiHhk1ymP2UUc25oDWpLXlfcRULJJlo/KfZZF
      3pmKwIq3CilGayFUi1NNwuavG76EcAVtVFUVFFIITwkhkuRbBHIytzEHYosFgD5/acK0Pauq
      JnwrwKv0nWq3aK7nKiALAD+iZvPNjFZau3/APqLEmvmRnAElmugcHsWREFxMMjMMVgYFiYKU
      AJO8u46eiQI4BBMBAgAiBQJVpZ9uAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRD3
      YiFXLFJgnbRfEAC9Uai7Rv20QIDlDogRzd+Vebg4ahyoUdj0CH+nAk40RIoq6G26u1e+sdgj
      pCa8jF6vrx+smpgd1HeJdmpahUX0XN3X9f9qU9oj9A4I1WDalRWJh+tP5WNv2ySy6AwcP9Qn
      juBMRTnTK27pk1sEMg9oJHK5p+ts8hlSC4SluyMKH5NMVy9c+A9yqq9NF6M6d6/ehKfBFFLG
      9BX+XLBATvf1ZemGVHQusCQebTGv0C0V9yqtdPdRWVIEhHxyNHATaVYOafTj/EF0lDxLl6zD
      T6trRV5n9F1VCEh4Aal8L5MxVPcIZVO7NHT2EkQgn8CvWjV3oKl2GopZF8V4XdJRl90U/WDv
      /6cmfI08GkzDYBHhS8ULWRFwGKobsSTyIvnbk4NtKdnTGyTJCQ8+6i52s+C54PiNgfj2ieNn
      6oOR7d+bNCcG1CdOYY+ZXVOcsjl73UYvtJrO0Rl/NpYERkZ5d/tzw4jZ6FCXgggA/Zxcjk6Y
      1ZvIm8Mt8wLRFH9Nww+FVsCtaCXJLP8DlJLASMD9rl5QS9Ku3u7ZNrr5HWXPHXITX660jgly
      shch6CWeiUATqjIAzkEQom/kEnOrvJAtkypRJ59vYQOedZ1sFVELMXg2UCkD/FwojfnVtjzY
      aTCeGwFQeqzHmM241iuOmBYPeyTY5veF49aBJA1gEJOQTvBR8Q==
      =Yhur
      -----END PGP PUBLIC KEY BLOCK-----
power_state:
 mode: reboot
 timeout: 10
 condition: True
